# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "builds app and runs ui tests"
  lane :test do
	run_tests(project: 'SauceTest.xcodeproj') 
  end
   lane :build do

update_project_provisioning(
  xcodeproj: "SauceTest.xcodeproj",
  profile: "SauceTesttSamBitrise.mobileprovision", # optional if you use sigh
  build_configuration: "Release",
  code_signing_identity: 'iPhone Distribution: Nice Agency Limited' # optionally specify the codesigning identity
)

  	 gym(project: 'SauceTest.xcodeproj',
  	 	codesigning_identity: 'iPhone Distribution: Nice Agency Limited',
  	 	export_method: 'enterprise')
   end
end



