# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "builds app and runs ui tests"
  lane :test do
	run_tests(project: 'SauceTest.xcodeproj') 
  end

   lane :build do
  	 gym(project: 'SauceTest.xcodeproj',
  	 	codesigning_identity: 'iPhone Distribution: Nice Agency Limited',
      export_options: {
  method: "enterprise",
  provisioningProfiles: { 
    "agency.nice.SauceTestt" => "SauceTesttSamBitrise"
  },
  teamID: "6PR9BVQYVX"
})
   end

lane :simulator do

  xcodebuild(project: 'SauceTest.xcodeproj',
           scheme: "SauceTest",
           xcargs: "-configuration 'Debug' -sdk 'iphonesimulator' -destination 'platform=iOS Simulator,name=iPhone 6,OS=12.0'"
           )
zip(path: "SauceTest.app",
    output_path: "Latest.app.zip"
)
 end 
end



