# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "builds app and runs ui tests"
  lane :test do
	run_tests(project: 'SauceTest.xcodeproj',
            output_directory: ENV['BITRISE_SOURCE_DIR']) 
  end

   lane :build do

project = Xcodeproj::Project.open('../SauceTest.xcodeproj')
project.targets.each do |target|
   target.build_configurations.each do |config|
     config.build_settings['CODE_SIGN_STYLE'] = "Manual"
  end
end
project.save

  	 gym(project: 'SauceTest.xcodeproj',
  	 	codesigning_identity: 'iPhone Distribution: Nice Agency Limited',
      export_options: {
  method: "enterprise",
  provisioningProfiles: { 
    "agency.nice.SauceTestt" => "SauceTesttSamBitrise"
  },
  teamID: "6PR9BVQYVX"
})
   end

lane :simulator do

  xcodebuild(project: 'SauceTest.xcodeproj',
           scheme: "SauceTest",
           configuration: "Debug",
           xcargs: "-sdk iphonesimulator SYMROOT=\"#{ENV['BITRISE_SOURCE_DIR']}/\""
           )

zip(path: "#{ENV['BITRISE_SOURCE_DIR']}/Debug-iphonesimulator/SauceTest.app",
  output_path: "#{ENV['BITRISE_SOURCE_DIR']}/SauceTest.zip")
 end 
end



